import { create } from 'zustand';

type Language = 'PT' | 'EN';

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  PT: {
    'nav.problema': 'Problema',
    'nav.solucao': 'Solução',
    'nav.acoes': 'Ações',
    'nav.combo': 'Combo',
    'nav.impacto': 'Impacto',
    'nav.financeiro': 'Financeiro',
    'nav.identidade': 'Identidade',
    'nav.sobre': 'Sobre',
    'hero.rebrand': 'Rebrand Sustentável',
    'hero.tagline': '"Dos campos de café até o seu copo,\na natureza é a prioridade."',
    'hero.cta': 'Comece a leitura',
    'hero.scroll': 'Role para baixo',
    'hero.chapters': '07 capítulos',
    'chapter.diagnostic': 'Capítulo 01 — Diagnóstico',
    'chapter.diagnostic.title': 'O que o\nStarbucks\ncausa.',
    'chapter.diagnostic.desc': 'Por trás de cada copo, há um custo ambiental que precisa ser repensado. O diagnóstico não é confortável — mas é o ponto de partida para qualquer rebrand honesto.',
    'chapter.response': 'Capítulo 02 — Resposta',
    'chapter.response.title': 'Mesma sereia.\nNovas raízes.',
    'chapter.response.desc1': 'Starroots mantém a alma do café que você conhece — mas planta novas bases. Roots são raízes, origem, natureza: o ponto onde a marca se reconecta com a terra.',
    'chapter.response.desc2': 'Uma identidade que cresce a partir do que sustenta o produto: o solo, as plantações, as comunidades. Cada elemento — da sereia coroada de folhas às embalagens kraft — fala essa mesma língua.',
    'chapter.pilares': 'Capítulo 03 — Pilares',
    'chapter.pilares.title': 'Ações que regeneram.',
    'chapter.pilares.desc': 'Quatro frentes integradas — ambiental, econômica e social — operando como um sistema vivo.',
    'chapter.launch': 'Capítulo 04 — Lançamento',
    'chapter.launch.title': 'Conheça o\nCombo Starroots.',
    'chapter.launch.subtitle': 'Exclusivo. Sustentável. Com o seu nome.',
    'chapter.launch.desc': 'O Combo Starroots é mais do que uma compra — é uma experiência. Sua bebida vem no copo biodegradável que, após o uso, vira adubo nas plantações de café. E o cookie artesanal? Feito com o seu nome.',
    'chapter.calculate': 'Capítulo 05 — Calcule',
    'chapter.calculate.title': 'Seu café,\nseu impacto.',
    'chapter.calculate.desc': 'Mova o controle e descubra quanto CO₂ você evita e quanto adubo retorna ao solo todo mês.',
    'chapter.business': 'Capítulo 06 — Business Case',
    'chapter.business.title': 'Um projeto que\nse paga sozinho.',
    'chapter.business.desc': 'Dos custos operacionais ao retorno final — todos os números fecham a conta.',
    'chapter.lookbook': 'Capítulo 07 — Lookbook',
    'chapter.lookbook.title': 'Aplicações\nda marca.',
    'chapter.lookbook.desc': 'Folhas integradas à sereia, paleta verde-kraft e embalagens em papel reciclado — cada peça reforça a narrativa de origem.',
    'footer.developedBy': 'Projeto desenvolvido por',
    'footer.tagline': '"Dos campos de café até o seu copo,\na natureza é a prioridade."',
    'marquee.roots': 'Raízes',
    'marquee.sustainability': 'Sustentabilidade',
    'marquee.composting': 'Compostagem',
    'marquee.cleanEnergy': 'Energia limpa',
    'marquee.community': 'Comunidade',
    'marquee.responsibleCoffee': 'Café responsável',
    'marquee.origin': 'Origem',
    'marquee.electricFleet': 'Frota elétrica',
    'problem.stat1.unit': 'copos / ano',
    'problem.stat1.title': 'Descartáveis com plástico',
    'problem.stat1.text': 'Mais de 6 bilhões de copos por ano com revestimento plástico interno — não recicláveis em larga escala.',
    'problem.stat2.unit': 'CO₂ vs 2019',
    'problem.stat2.title': 'Emissões em alta',
    'problem.stat2.text': 'Logística global gera emissões massivas. Em 2024 os níveis seguem acima do patamar pré-pandemia.',
    'problem.stat3.unit': 'diariamente',
    'problem.stat3.title': 'Desperdício alimentar',
    'problem.stat3.text': 'Toneladas de alimentos descartadas todos os dias nas lojas ao redor do mundo, sem reaproveitamento.',
    'problem.stat4.unit': 'consumo intenso',
    'problem.stat4.title': 'Energia & água',
    'problem.stat4.text': 'Alto consumo energético e hídrico em milhares de operações simultâneas, com pouca recuperação.',
    'solution.origin.title': 'Origem',
    'solution.origin.text': 'Café e plantação como ponto de partida.',
    'solution.sustainability.title': 'Sustentabilidade',
    'solution.sustainability.text': 'Natureza e ambiente no centro da experiência.',
    'solution.community.title': 'Comunidade',
    'solution.community.text': 'Pessoas e impacto social como raiz da marca.',
    'solution.economy.title': 'Economia',
    'solution.economy.text': 'Lucro conectado à circularidade e retorno local.',
    'solution.innovation.title': 'Inovação',
    'solution.innovation.text': 'Tecnologia elétrica para reduzir o caminho até você.',
    'action.1.tag': 'Ambiental',
    'action.1.title': 'Copo que vira adubo',
    'action.1.text': 'Copos PLA biodegradáveis se decompõem e retornam às plantações de café como adubo. Economia circular real.',
    'action.2.tag': 'Ambiental',
    'action.2.title': 'Energia limpa',
    'action.2.text': 'Frota de entrega 100% elétrica, energia solar nas lojas e estações de carregamento abertas ao público.',
    'action.3.tag': 'Econômica',
    'action.3.title': 'Combo Starroots',
    'action.3.text': 'Bebida + cookie personalizado com o nome do cliente por R$12,50 — receita que financia toda a logística verde.',
    'action.4.tag': 'Social',
    'action.4.title': 'Educação ambiental',
    'action.4.text': 'Parcerias com ONGs para conscientização ambiental de crianças e adolescentes em comunidades.',
    'combo.title1': 'O copo que tem nome.',
    'combo.title2': 'O cookie que é só seu.',
    'combo.included.label': 'O que está incluso',
    'combo.included.title': 'Três elementos. Um propósito.',
    'combo.item1.title': 'Bebida',
    'combo.item1.text': 'À sua escolha, no copo biodegradável Starroots.',
    'combo.item2.title': 'Cookie',
    'combo.item2.text': 'Artesanal, feito na hora, com o seu nome.',
    'combo.item3.title': 'Impacto',
    'combo.item3.text': 'Cada compra financia a logística sustentável.',
    'combo.price.label': 'Por apenas',
    'combo.price.value': 'R$12,50',
    'combo.price.desc': 'Um combo que cuida de você e do planeta.',
    'combo.cta': 'Quero meu combo',
    'combo.availability': 'Disponível nas unidades participantes',
    'combo.circularity.label': 'Economia circular',
    'combo.circularity.text': 'Seu copo de hoje vira o adubo do café de amanhã.',
    'combo.exclusivity.label': 'Por que é exclusivo',
    'combo.exclusivity.title': 'Único. Numerado. Ilimitado.',
    'combo.exclusivity.item1': 'Cada cookie é feito na hora com o seu nome',
    'combo.exclusivity.item2': 'O copo é numerado — nenhum é igual ao outro',
    'combo.exclusivity.item3': 'Disponível em todas as unidades participantes',
    'combo.exclusivity.quote': '"Porque sustentabilidade também pode ser especial."',
    'impact.cupsMonth': 'Copos por mês',
    'impact.co2Saved': 'CO₂ evitado',
    'impact.compostGenerated': 'Adubo gerado',
    'impact.perMonth': 'por mês',
    'impact.viaComposting': 'via compostagem',
    'impact.messageLabel': 'Mensagem',
    'impact.m1': 'Pequenos gestos plantam grandes florestas.',
    'impact.m2': 'Você já está virando parte da raiz.',
    'impact.m3': 'Seu café move um ciclo inteiro de vida.',
    'impact.m4': 'Você é solo fértil para a próxima safra.',
    'impact.m5': 'Você é, literalmente, uma floresta em movimento.',
    'financial.tag1': 'Problema',
    'financial.card1.title': 'Copo Atual',
    'financial.card1.detail1': '4B copos plásticos × US$0,07',
    'financial.card1.detail2': 'Revestimento plástico — não recicláveis',
    'financial.tag2': 'Investimento',
    'financial.card2.title': 'Copo PLA',
    'financial.card2.detail1': '4B copos biodegradáveis × US$0,12',
    'financial.card2.detail2': 'Custo adicional de US$200M/ano',
    'financial.tag3': 'Retorno',
    'financial.card3.title': 'Economia',
    'financial.card3.detail1': 'Compostagem dos copos vira adubo',
    'financial.card3.detail2': '15% do adubo poluente substituído',
    'financial.tag4': 'Resultado',
    'financial.card4.title': 'Lucro Final',
    'financial.card4.detail1': 'Lucro atual: US$3,5B',
    'financial.card4.detail2': '+ Cookie (30% clientes): US$1,8B',
    'financial.card4.detail3': '+46% sobre lucro atual',
    'financial.footer': 'Se 30% dos clientes escolherem o combo Starroots → lucro salta de US$3,5B para US$5,1B (+46%)',
    'lookbook.caption1': '01 — Identidade no ponto de venda',
    'lookbook.caption2': '02 — Embalagem primária',
    'lookbook.caption3': '03 — Material kraft',
    'manifesto.title': 'Starroots não é\nsó uma marca.\nÉ um movimento.',
    'about.hero.title': 'A história por trás das raízes.',
    'about.hero.subtitle': 'Um projeto escolar que virou um movimento real.',
    'about.origin.tag': 'A Origem',
    'about.origin.title': 'O projeto nasceu de uma aula de sustentabilidade no curso técnico de administração da Escola Estadual Catarina Jorge Gonçalves em Contagem-MG.',
    'about.origin.text': 'A professora desafiou o grupo a escolher uma empresa real e propor mudanças sustentáveis genuínas. Escolheram o Starbucks para repensar como uma gigante mundial poderia adotar práticas de economia circular de forma viável e impactante.',
    'about.team.tag': 'A Equipe',
    'about.team.title': 'Os idealizadores do Starroots',
    'about.team.member1.role': 'PARTE ESCRITA E PESQUISA',
    'about.team.member2.role': 'ANÁLISE FINANCEIRA E DADOS',
    'about.team.member3.role': 'DESIGN, IDENTIDADE VISUAL E DESENVOLVIMENTO',
    'about.milestones.tag': 'Marcos',
    'about.milestones.title': 'O Reconhecimento',
    'about.milestones.item1': 'A professora amou o projeto e pediu pra apresentar em cada sala da escola.',
    'about.milestones.item2': 'O grupo entrou em contato com o Starbucks Brasil.',
    'about.milestones.item3': 'O Starbucks respondeu positivamente e encaminhou para a área responsável.',
    'about.final.cta': 'Comprar Agora',
  },
  EN: {
    'nav.problema': 'Problem',
    'nav.solucao': 'Solution',
    'nav.acoes': 'Actions',
    'nav.combo': 'Combo',
    'nav.impacto': 'Impact',
    'nav.financeiro': 'Financial',
    'nav.identidade': 'Identity',
    'nav.sobre': 'About',
    'hero.rebrand': 'Sustainable Rebrand',
    'hero.tagline': '"From the coffee fields to your cup,\nnature is the priority."',
    'hero.cta': 'Start reading',
    'hero.scroll': 'Scroll down',
    'hero.chapters': '07 chapters',
    'chapter.diagnostic': 'Chapter 01 — Diagnosis',
    'chapter.diagnostic.title': 'What\nStarbucks\ncauses.',
    'chapter.diagnostic.desc': 'Behind every cup, there is an environmental cost that needs to be rethought. The diagnosis is not comfortable — but it is the starting point for any honest rebrand.',
    'chapter.response': 'Chapter 02 — Response',
    'chapter.response.title': 'Same siren.\nNew roots.',
    'chapter.response.desc1': 'Starroots keeps the soul of the coffee you know — but plants new foundations. Roots are origin, nature: the point where the brand reconnects with the earth.',
    'chapter.response.desc2': 'An identity that grows from what sustains the product: the soil, the plantations, the communities. Every element — from the leaf-crowned siren to the kraft packaging — speaks this same language.',
    'chapter.pilares': 'Chapter 03 — Pillars',
    'chapter.pilares.title': 'Actions that regenerate.',
    'chapter.pilares.desc': 'Four integrated fronts — environmental, economic, and social — operating as a living system.',
    'chapter.launch': 'Chapter 04 — Launch',
    'chapter.launch.title': 'Meet the\nStarroots Combo.',
    'chapter.launch.subtitle': 'Exclusive. Sustainable. With your name.',
    'chapter.launch.desc': 'The Starroots Combo is more than a purchase — it is an experience. Your drink comes in a biodegradable cup that, after use, becomes fertilizer in the coffee plantations. And the artisanal cookie? Made with your name.',
    'chapter.calculate': 'Chapter 05 — Calculate',
    'chapter.calculate.title': 'Your coffee,\nyour impact.',
    'chapter.calculate.desc': 'Move the slider and find out how much CO₂ you avoid and how much fertilizer returns to the soil every month.',
    'chapter.business': 'Chapter 06 — Business Case',
    'chapter.business.title': 'A project that\npays for itself.',
    'chapter.business.desc': 'From operational costs to the final return — all the numbers add up.',
    'chapter.lookbook': 'Chapter 07 — Lookbook',
    'chapter.lookbook.title': 'Brand\nApplications.',
    'chapter.lookbook.desc': 'Leaves integrated into the siren, green-kraft palette, and recycled paper packaging — each piece reinforces the origin narrative.',
    'footer.developedBy': 'Project developed by',
    'footer.tagline': '"From the coffee fields to your cup,\nnature is the priority."',
    'marquee.roots': 'Roots',
    'marquee.sustainability': 'Sustainability',
    'marquee.composting': 'Composting',
    'marquee.cleanEnergy': 'Clean Energy',
    'marquee.community': 'Community',
    'marquee.responsibleCoffee': 'Responsible Coffee',
    'marquee.origin': 'Origin',
    'marquee.electricFleet': 'Electric Fleet',
    'problem.stat1.unit': 'cups / year',
    'problem.stat1.title': 'Disposables with plastic',
    'problem.stat1.text': 'More than 6 billion cups per year with internal plastic lining — not recyclable on a large scale.',
    'problem.stat2.unit': 'CO₂ vs 2019',
    'problem.stat2.title': 'Emissions rising',
    'problem.stat2.text': 'Global logistics generate massive emissions. In 2024, levels remain above the pre-pandemic level.',
    'problem.stat3.unit': 'daily',
    'problem.stat3.title': 'Food waste',
    'problem.stat3.text': 'Tons of food discarded every day in stores around the world, without reuse.',
    'problem.stat4.unit': 'intense consumption',
    'problem.stat4.title': 'Energy & water',
    'problem.stat4.text': 'High energy and water consumption in thousands of simultaneous operations, with little recovery.',
    'solution.origin.title': 'Origin',
    'solution.origin.text': 'Coffee and plantation as a starting point.',
    'solution.sustainability.title': 'Sustainability',
    'solution.sustainability.text': 'Nature and environment at the center of the experience.',
    'solution.community.title': 'Community',
    'solution.community.text': 'People and social impact as the brand root.',
    'solution.economy.title': 'Economy',
    'solution.economy.text': 'Profit connected to circularity and local return.',
    'solution.innovation.title': 'Innovation',
    'solution.innovation.text': 'Electric technology to reduce the path to you.',
    'action.1.tag': 'Environmental',
    'action.1.title': 'Cup that turns into fertilizer',
    'action.1.text': 'Biodegradable PLA cups decompose and return to coffee plantations as fertilizer. Real circular economy.',
    'action.2.tag': 'Environmental',
    'action.2.title': 'Clean energy',
    'action.2.text': '100% electric delivery fleet, solar energy in stores and charging stations open to the public.',
    'action.3.tag': 'Economic',
    'action.3.title': 'Starroots Combo',
    'action.3.text': 'Drink + personalized cookie with the customer\'s name for $12.50 — revenue that finances all green logistics.',
    'action.4.tag': 'Social',
    'action.4.title': 'Environmental education',
    'action.4.text': 'Partnerships with NGOs for environmental awareness of children and adolescents in communities.',
    'combo.title1': 'The cup with a name.',
    'combo.title2': 'The cookie that is only yours.',
    'combo.included.label': 'What\'s included',
    'combo.included.title': 'Three elements. One purpose.',
    'combo.item1.title': 'Drink',
    'combo.item1.text': 'Your choice, in the Starroots biodegradable cup.',
    'combo.item2.title': 'Cookie',
    'combo.item2.text': 'Handcrafted, made to order, with your name.',
    'combo.item3.title': 'Impact',
    'combo.item3.text': 'Every purchase finances sustainable logistics.',
    'combo.price.label': 'For only',
    'combo.price.value': '$12.50',
    'combo.price.desc': 'A combo that cares for you and the planet.',
    'combo.cta': 'I want my combo',
    'combo.availability': 'Available at participating units',
    'combo.circularity.label': 'Circular economy',
    'combo.circularity.text': 'Today\'s cup becomes tomorrow\'s coffee fertilizer.',
    'combo.exclusivity.label': 'Why it\'s exclusive',
    'combo.exclusivity.title': 'Unique. Numbered. Unlimited.',
    'combo.exclusivity.item1': 'Each cookie is made to order with your name',
    'combo.exclusivity.item2': 'The cup is numbered — no two are the same',
    'combo.exclusivity.item3': 'Available at all participating units',
    'combo.exclusivity.quote': '"Because sustainability can also be special."',
    'impact.cupsMonth': 'Cups per month',
    'impact.co2Saved': 'CO₂ saved',
    'impact.compostGenerated': 'Compost generated',
    'impact.perMonth': 'per month',
    'impact.viaComposting': 'via composting',
    'impact.messageLabel': 'Message',
    'impact.m1': 'Small gestures plant large forests.',
    'impact.m2': 'You are already becoming part of the root.',
    'impact.m3': 'Your coffee moves an entire cycle of life.',
    'impact.m4': 'You are fertile soil for the next crop.',
    'impact.m5': 'You are, literally, a forest in motion.',
    'financial.tag1': 'Problem',
    'financial.card1.title': 'Current Cup',
    'financial.card1.detail1': '4B plastic cups × US$0.07',
    'financial.card1.detail2': 'Plastic lining — non-recyclable',
    'financial.tag2': 'Investment',
    'financial.card2.title': 'PLA Cup',
    'financial.card2.detail1': '4B biodegradable cups × US$0.12',
    'financial.card2.detail2': 'Additional cost of US$200M/year',
    'financial.tag3': 'Return',
    'financial.card3.title': 'Economy',
    'financial.card3.detail1': 'Composting of cups becomes fertilizer',
    'financial.card3.detail2': '15% of polluting fertilizer replaced',
    'financial.tag4': 'Result',
    'financial.card4.title': 'Final Profit',
    'financial.card4.detail1': 'Current profit: US$3.5B',
    'financial.card4.detail2': '+ Cookie (30% customers): US$1.8B',
    'financial.card4.detail3': '+46% over current profit',
    'financial.footer': 'If 30% of customers choose the Starroots combo → profit jumps from US$3.5B to US$5.1B (+46%)',
    'lookbook.caption1': '01 — Identity at the point of sale',
    'lookbook.caption2': '02 — Primary packaging',
    'lookbook.caption3': '03 — Kraft material',
    'manifesto.title': 'Starroots is not\njust a brand.\nIt\'s a movement.',
    'about.hero.title': 'The story behind the roots.',
    'about.hero.subtitle': 'A school project that turned into a real movement.',
    'about.origin.tag': 'The Origin',
    'about.origin.title': 'The project was born from a sustainability class in the administration technical course at Catarina Jorge Gonçalves State School in Contagem-MG.',
    'about.origin.text': 'The teacher challenged the group to choose a real company and propose genuine sustainable changes. They chose Starbucks to rethink how a global giant could adopt circular economy practices in a viable and impactful way.',
    'about.team.tag': 'The Team',
    'about.team.title': 'The idealizers of Starroots',
    'about.team.member1.role': 'WRITTEN PART AND RESEARCH',
    'about.team.member2.role': 'FINANCIAL ANALYSIS AND DATA',
    'about.team.member3.role': 'DESIGN, VISUAL IDENTITY AND DEVELOPMENT',
    'about.milestones.tag': 'Milestones',
    'about.milestones.title': 'Recognition',
    'about.milestones.item1': 'The teacher loved the project and asked to present it in every classroom at the school.',
    'about.milestones.item2': 'The group contacted Starbucks Brazil.',
    'about.milestones.item3': 'Starbucks responded positively and forwarded it to the responsible area.',
    'about.final.cta': 'Buy Now',
  }
};

export const useLanguage = create<LanguageState>((set, get) => ({
  language: 'PT',
  setLanguage: (lang) => set({ language: lang }),
  t: (key) => translations[get().language][key] || key,
}));
