import { useMemo, useState } from "react";
import { FadeInSection } from "./FadeInSection";
import { Slider } from "@/components/ui/slider";

// Approximate impact factors per disposable cup avoided:
// - CO₂ saved: ~110g per cup (production + disposal vs PLA)
// - Compost generated by composting one PLA cup: ~12g of finished adubo
const CO2_PER_CUP = 110;
const COMPOST_PER_CUP = 12;

function motivational(cups: number) {
  if (cups <= 5) return "Pequenos gestos plantam grandes florestas.";
  if (cups <= 15) return "Você já está virando parte da raiz.";
  if (cups <= 30) return "Seu café move um ciclo inteiro de vida.";
  if (cups <= 60) return "Você é solo fértil para a próxima safra.";
  return "Você é, literalmente, uma floresta em movimento.";
}

function format(n: number) {
  if (n >= 1000) return (n / 1000).toFixed(n >= 10000 ? 0 : 1) + " kg";
  return Math.round(n).toLocaleString("pt-BR") + " g";
}

export function ImpactCalculator() {
  const [cups, setCups] = useState(20);

  const { co2, compost, phrase } = useMemo(() => {
    return {
      co2: cups * CO2_PER_CUP,
      compost: cups * COMPOST_PER_CUP,
      phrase: motivational(cups),
    };
  }, [cups]);

  return (
    <section
      id="impacto"
      className="scroll-anchor px-6 md:px-10 py-32"
      style={{ backgroundColor: "#1a3d2b" }}
    >
      <div className="max-w-[1400px] mx-auto">
        <div className="grid grid-cols-1 md:grid-cols-12 gap-10 mb-16 items-end">
          <FadeInSection className="md:col-span-7">
            <p className="text-[10px] tracking-[0.4em] uppercase text-accent mb-6">Capítulo 05 — Calcule</p>
            <h2
              className="font-display font-black leading-[0.9] tracking-[-0.03em]"
              style={{ fontSize: "clamp(2.5rem, 6vw, 5.5rem)" }}
            >
              Seu café,<br /><em className="italic font-semibold text-accent">seu impacto.</em>
            </h2>
          </FadeInSection>
          <FadeInSection delay={0.15} className="md:col-span-4 md:col-start-9">
            <p className="text-base text-foreground/70 leading-relaxed font-body">
              Mova o controle e descubra quanto CO₂ você evita e quanto adubo retorna ao solo todo mês.
            </p>
          </FadeInSection>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-px bg-border/40">
          {/* Slider panel */}
          <FadeInSection className="lg:col-span-5 bg-background p-10 md:p-12 top-rule">
            <p className="text-[10px] tracking-[0.4em] uppercase text-foreground/50 mb-6">
              Copos por mês
            </p>
            <p
              className="font-display font-black leading-none tracking-[-0.04em] mb-10 text-foreground"
              style={{ fontSize: "clamp(5rem, 12vw, 11rem)" }}
            >
              {cups}
            </p>
            <Slider
              value={[cups]}
              onValueChange={(v) => setCups(v[0] ?? 0)}
              min={0}
              max={100}
              step={1}
              aria-label="Quantidade de copos por mês"
            />
            <div className="flex justify-between text-[10px] tracking-[0.3em] uppercase text-foreground/40 mt-4">
              <span>0</span>
              <span>50</span>
              <span>100</span>
            </div>
          </FadeInSection>

          {/* Results panel */}
          <FadeInSection delay={0.1} className="lg:col-span-7 bg-background grid grid-cols-1 sm:grid-cols-2">
            <div className="p-10 md:p-12 sm:border-r border-border/40" style={{ borderTop: "3px solid var(--chart-2)" }}>
              <p className="text-[10px] tracking-[0.3em] uppercase text-foreground/50 mb-4">CO₂ evitado</p>
              <p
                key={`co2-${cups}`}
                className="font-display font-black leading-[0.9] tracking-[-0.04em] text-foreground animate-rise"
                style={{ fontSize: "clamp(2.5rem, 5vw, 4.5rem)" }}
              >
                {format(co2)}
              </p>
              <p className="text-sm text-foreground/60 mt-4 font-body">por mês</p>
            </div>
            <div className="p-10 md:p-12" style={{ borderTop: "3px solid var(--accent)" }}>
              <p className="text-[10px] tracking-[0.3em] uppercase text-foreground/50 mb-4">Adubo gerado</p>
              <p
                key={`comp-${cups}`}
                className="font-display font-black leading-[0.9] tracking-[-0.04em] text-foreground animate-rise"
                style={{ fontSize: "clamp(2.5rem, 5vw, 4.5rem)" }}
              >
                {format(compost)}
              </p>
              <p className="text-sm text-foreground/60 mt-4 font-body">via compostagem</p>
            </div>
            <div className="sm:col-span-2 p-10 md:p-12 border-t border-border/40">
              <p className="text-[10px] tracking-[0.3em] uppercase text-accent mb-4">Mensagem</p>
              <p
                key={phrase}
                className="font-display italic text-2xl md:text-3xl leading-snug animate-rise"
              >
                "{phrase}"
              </p>
            </div>
          </FadeInSection>
        </div>
      </div>
    </section>
  );
}
